import type { Field, TowerDefenseDefinition } from "./model";
import { validateDefinition } from "./validation";

export type GeneratedFile = { path: string; content: string };

const luauType = (field: Field) => field.type === "u16" ? "number" : field.type;
const quote = (value: string) => JSON.stringify(value);

export function generateTowerDefense(definition: TowerDefenseDefinition): GeneratedFile[] {
  const diagnostics = validateDefinition(definition);
  if (diagnostics.length) throw new Error(diagnostics.map((item) => `${item.path}: ${item.message}`).join("\n"));
  const messageTypes = definition.messages.map((message) => `export type ${message.name} = {\n${message.fields.map((field) => `\t${field.name}: ${luauType(field)},`).join("\n")}\n}`).join("\n\n");
  const messages = definition.messages.map((message) => `\t${message.name} = { direction = ${quote(message.direction)} },`).join("\n");
  const targetModes = definition.targeting.map(quote).join(", ");
  return [
    { path: ".forge/tower-defense.json", content: JSON.stringify(definition, null, 2) + "\n" },
    { path: "wally.toml", content: `[package]\nname = "generated/${definition.name.toLowerCase().replace(/[^a-z0-9]+/g, "-")}"\nversion = "0.1.0"\nregistry = "https://github.com/UpliftGames/wally-index"\n\n[dependencies]\nLync = "axp3cter/lync@0.0.0"\nJECS = "ukendio/jecs@0.0.0"\n` },
    { path: "default.project.json", content: JSON.stringify({ name: definition.name, tree: { $className: "DataModel", ReplicatedStorage: { Shared: { $path: "src/shared" } }, ServerScriptService: { Server: { $path: "src/server" } }, StarterPlayer: { StarterPlayerScripts: { Client: { $path: "src/client" } } } } }, null, 2) + "\n" },
    { path: "src/shared/domain/TowerDefenseConfig.luau", content: `-- Generated by Roblox Forge. Use the named user-code region for supported custom logic.\n\nexport type TargetMode = ${definition.targeting.map(quote).join(" | ")}\n\n-- <forge:user-code id="targeting-extensions">\n-- Add pure targeting helpers here. This region survives regeneration.\n-- </forge:user-code>\n\nreturn {\n\ttopology = ${quote(definition.topology)},\n\teconomy = ${quote(definition.economy)},\n\ttargetModes = { ${targetModes} },\n}\n` },
    { path: "src/shared/schemas/Network.luau", content: `-- Generated Lync-facing contract types.\n\n${messageTypes}\n\nreturn {\n${messages}\n}\n` },
    { path: "src/shared/domain/Simulation.luau", content: `-- Pure domain boundary: safe to exercise under Lute once dependencies are installed.\n\nexport type State = { wave: number, currency: number, lives: number }\n\nlocal Simulation = {}\n\n-- <forge:user-code id="simulation-extensions">\n-- Add pure domain helpers here. This region survives regeneration.\n-- </forge:user-code>\n\nfunction Simulation.step(state: State): State\n\tassert(state.lives >= 0, "lives cannot be negative")\n\treturn { wave = state.wave + 1, currency = state.currency, lives = state.lives }\nend\n\nreturn Simulation\n` },
    { path: "tests/domain/Simulation.spec.luau", content: `local Simulation = require(script.Parent.Parent.Parent.src.shared.domain.Simulation)\n\nreturn function()\n\tlocal nextState = Simulation.step({ wave = 0, currency = 500, lives = 20 })\n\tassert(nextState.wave == 1)\n\tassert(nextState.lives == 20)\nend\n` }
  ];
}
